apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonLabels:
  app.kubernetes.io/component: frontend

patches:
  - target:
      kind: Deployment
      name: service
    options:
      allowNameChange: true
    patch: |-
      kind: Deployoment
      metadata:
        name: frontend
      spec:
        template:
          spec:
            containers:
              - name: service
                env:
                  - name: SERVICES
                    value: frontend
                ports:
                  - name: grpc
                    containerPort: 7233
                  - name: membership
                    containerPort: 6933

                # Frontend is the only service that has a v1.Service.
                # A headless variant (DNS records only) & a load-balanced one.
                # This probe determines which Pods are ready to serve traffic.
                readinessProbe:
                  tcpSocket:
                    port: grpc
                  failureThreshold: 3
                  successThreshold: 1
                  periodSeconds: 10
                  timeoutSeconds: 1
