apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: datastore
manifests:
  kustomize: {}
profiles:
  - name: pg13
    deploy:
      helm:
        releases:
          - name: postgresql
            remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
            # Not the Postgres version!!
            version: 13.0.0
            namespace: temporal-ds-pg13
            createNamespace: true
            setValues:
              image:
                tag: 13.12.0-debian-11-r48
              auth:
                enablePostgresUser: true
                postgresPassword: postgres
                username: temporal
                password: temporal
                database: temporal
