apiVersion: skaffold/v4beta6
kind: Config
requires:
  - path: ./datastore/skaffold.yaml
    activeProfiles:
      - name: pg13
        activatedBy:
          - pg13
metadata:
  name: temporal
profiles:
  - name: pg13
    deploy:
      kubectl: {}
    manifests:
      kustomize:
        paths:
          - ./kustomize/overlays/postgres13/
