apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonLabels:
  app.kubernetes.io/component: matching

patches:
  - target:
      kind: Deployment
      name: service
    options:
      allowNameChange: true
    patch: |-
      kind: Deployoment
      metadata:
        name: matching
      spec:
        template:
          spec:
            containers:
              - name: service
                env:
                  - name: SERVICES
                    value: matching
                ports:
                  - name: grpc
                    containerPort: 7235
                  - name: membership
                    containerPort: 6935
