# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/deployment-apps-v1.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ui
    spec:
      enableServiceLinks: false
      containers:
        - name: ui
          image: temporalio/ui
          env:
            - name: TEMPORAL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: static-config-env
                  key: TEMPORAL_ADDRESS
                  optional: false

            - name: TEMPORAL_CLI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: static-config-env
                  key: TEMPORAL_CLI_ADDRESS
                  optional: true
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            failureThreshold: 5
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 1
            httpGet:
              port: http
          readinessProbe:
            httpGet:
              port: http
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 1
