# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/service.json

apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: ui
