# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-tools
  labels:
    app.kubernetes.io/component: admin-tools
  annotations:
    description: |-
      A standby workload w/ tools like tctl that's helpful for debugging and admin tasks.
      By default it runs zero replicas, so scale it when you need it.
      This is a StatefulSet for more memorable Pod names.
      For example, `kubectl scale sts/temporal-admin-tools --replicas=1` and
      then `kubectl exec -it temporal-admin-tools-0`.
spec:
  replicas: 0
  serviceName: admin-tools
  selector:
    matchLabels:
      app.kubernetes.io/component: admin-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admin-tools
    spec:
      enableServiceLinks: false
      containers:
        - name: admin-tools
          image: temporalio/admin-tools
          env:
            - name: TEMPORAL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: static-config-env
                  key: TEMPORAL_ADDRESS
                  optional: false

            - name: TEMPORAL_CLI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: static-config-env
                  key: TEMPORAL_CLI_ADDRESS
                  optional: true
