# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/service.json

apiVersion: v1
kind: Service
metadata:
  name: admin-tools
  labels:
    app.kubernetes.io/component: admin-tools
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/component: admin-tools
