apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonLabels:
  app.kubernetes.io/component: worker

patches:
  - target:
      kind: Deployment
      name: service
    options:
      allowNameChange: true
    patch: |-
      kind: Deployoment
      metadata:
        name: worker
      spec:
        template:
          spec:
            containers:
              - name: service
                env:
                  - name: SERVICES
                    value: worker
                ports:
                  - name: grpc
                    containerPort: 7239

                  - name: membership
                    containerPort: 6939
                livenessProbe:
                  tcpSocket:
                    port: membership
